version: '3.1'

services:

  wordpress:
    image: wordpress
    depends_on:
        - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  node:
    image: jcastelain/node-web-app
    restart: unless-stopped
    ports:
      - 49160:8080
    volumes:
      - ./appjs:/usr/src/app/appjs
      - ./server.js:/usr/src/app/server.js

volumes:
  wordpress:
  db:
  node:
